//Auth Types
export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_FAIL = 'FORGET_FAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_FAIL = 'CHANGE_FAIL';
export const LOGIN_BTN_LOADING = 'LOGIN_BTN_LOADING';
export const LOGOUT = 'LOGOUT';

//Degree Validation Types
export const SHOW_SUCCESS_APPLICATION = 'SHOW_SUCCESS_APPLICATION';
export const SHOW_SUCCESS_APPLICATION_ERROR = 'SHOW_SUCCESS_APPLICATION_ERROR';
export const SEARCH = 'SEARCH';

//Contact Us Types
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';

//Student Types
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const UPDATE_STUDENT_ERROR = 'UPDATE_STUDENT_ERROR';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR';
export const SHOW_STUDENT = 'SHOW_STUDENT';
export const SHOW_STUDENT_ERROR = 'SHOW_STUDENT_ERROR';
export const SHOW_STUDENT_BY_ID = 'SHOW_STUDENT_BY_ID';
export const SHOW_STUDENT_BY_ID_ERROR = 'SHOW_STUDENT_BY_ID_ERROR';
export const STUDENT_LOADING = 'STUDENT_LOADING';

//User Types
export const ADD_USER = 'ADD_USER';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const SHOW_USER = 'SHOW_USER';
export const SHOW_USER_ERROR = 'SHOW_USER_ERROR';
export const SHOW_USER_BY_ID = 'SHOW_USER_BY_ID';
export const SHOW_USER_BY_ID_ERROR = 'SHOW_USER_BY_ID_ERROR';
export const USER_LOADING = 'USER_LOADING';

//Department Types
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const ADD_DEPARTMENT_ERROR = 'ADD_DEPARTMENT_ERROR';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const UPDATE_DEPARTMENT_ERROR = 'UPDATE_DEPARTMENT_ERROR';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const DELETE_DEPARTMENT_ERROR = 'DELETE_DEPARTMENT_ERROR';
export const SHOW_DEPARTMENT = 'SHOW_DEPARTMENT';
export const SHOW_DEPARTMENT_ERROR = 'SHOW_DEPARTMENT_ERROR';
export const SHOW_DEPARTMENT_BY_ID = 'SHOW_DEPARTMENT_BY_ID';
export const SHOW_DEPARTMENT_BY_ID_ERROR = 'SHOW_DEPARTMENT_BY_ID_ERROR';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';

//Uplaod CSV File Types
export const UPLOAD_CSV_FILE = 'UPLOAD_CSV_FILE';
export const SET_UPLOAD_CSV_FILE = 'SET_UPLOAD_CSV_FILE';
export const UPLOAD_CSV_FILE_LOADING = 'UPLOAD_CSV_FILE_LOADING';
export const UPLOAD_CSV_FILE_ERROR = 'UPLOAD_CSV_FILE_ERROR';

//Degree Application Types
export const SHOW_DEGREE_APPLICATION = 'SHOW_DEGREE_APPLICATION';
export const SHOW_DEGREE_APPLICATION_ERROR = 'SHOW_DEGREE_APPLICATION_ERROR';
export const DELETE_DEGREE_APPLICATION = 'DELETE_DEGREE_APPLICATION';
export const DELETE_DEGREE_APPLICATION_ERROR =
'DELETE_DEGREE_APPLICATION_ERROR';
export const SHOW_DEGREE_APPLICATION_LOADING =
'SHOW_DEGREE_APPLICATION_LOADING';

//View Contact Us Types
export const SHOW_CONTACT = 'SHOW_CONTACT';
export const SHOW_CONTACT_ERROR = 'SHOW_CONTACT_ERROR';
export const SHOW_CONTACT_LOADING = 'SHOW_CONTACT_LOADING';

//View Feedback Types
export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const SHOW_FEEDBACK_ERROR = 'SHOW_FEEDBACK_ERROR';
export const SHOW_FEEDBACK_LOADING = 'SHOW_FEEDBACK_LOADING';

//Application Count Types
export const COUNT_LOADING = 'COUNT_LOADING';
export const SHOW_CS_DEPARTMENT_COUNT = 'SHOW_CS_DEPARTMENT_COUNT';
export const SHOW_CS_DEPARTMENT_COUNT_ERROR = 'SHOW_CS_DEPARTMENT_COUNT_ERROR';
export const SHOW_URDU_DEPARTMENT_COUNT = 'SHOW_URDU_DEPARTMENT_COUNT';
export const SHOW_URDU_DEPARTMENT_COUNT_ERROR =
  'SHOW_URDU_DEPARTMENT_COUNT_ERROR';
export const SHOW_ISLAMIAT_DEPARTMENT_COUNT = 'SHOW_ISLAMIAT_DEPARTMENT_COUNT';
export const SHOW_ISLAMIAT_DEPARTMENT_COUNT_ERROR =
  'SHOW_ISLAMIAT_DEPARTMENT_COUNT_ERROR';
export const SHOW_LAW_DEPARTMENT_COUNT = 'SHOW_LAW_DEPARTMENT_COUNT';
export const SHOW_LAW_DEPARTMENT_COUNT_ERROR =
  'SHOW_LAW_DEPARTMENT_COUNT_ERROR';
export const SHOW_ECONOMICS_DEPARTMENT_COUNT =
  'SHOW_ECONOMICS_DEPARTMENT_COUNT';
export const SHOW_ECONOMICS_DEPARTMENT_COUNT_ERROR =
  'SHOW_ECONOMICS_DEPARTMENT_COUNT_ERROR';
export const SHOW_BUSINESS_DEPARTMENT_COUNT = 'SHOW_BUSINESS_DEPARTMENT_COUNT';
export const SHOW_BUSINESS_DEPARTMENT_COUNT_ERROR =
  'SHOW_BUSINESS_DEPARTMENT_COUNT_ERROR';
export const SHOW_COMMERCE_DEPARTMENT_COUNT = 'SHOW_COMMERCE_DEPARTMENT_COUNT';
export const SHOW_COMMERCE_DEPARTMENT_COUNT_ERROR =
  'SHOW_COMMERCE_DEPARTMENT_COUNT_ERROR';
export const SHOW_APPLIED_PHYSICS_DEPARTMENT_COUNT =
  'SHOW_APPLIED_PHYSICS_DEPARTMENT_COUNT';
export const SHOW_APPLIED_PHYSICS_DEPARTMENT_COUNT_ERROR =
  'SHOW_APPLIED_PHYSICS_DEPARTMENT_COUNT_ERROR';
export const SHOW_ELECTRICAL_DEPARTMENT_COUNT =
  'SHOW_ELECTRICAL_DEPARTMENT_COUNT';
export const SHOW_ELECTRICAL_DEPARTMENT_COUNT_ERROR =
  'SHOW_ELECTRICAL_DEPARTMENT_COUNT_ERROR';
export const SHOW_MATHEMATICS_DEPARTMENT_COUNT =
  'SHOW_MATHEMATICS_DEPARTMENT_COUNT';
export const SHOW_MATHEMATICS_DEPARTMENT_COUNT_ERROR =
  'SHOW_MATHEMATICS_DEPARTMENT_COUNT_ERROR';
export const SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_COUNT =
  'SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_COUNT';
export const SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_COUNT_ERROR =
  'SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_COUNT_ERROR';
export const SHOW_ENGLISH_DEPARTMENT_COUNT = 'SHOW_ENGLISH_DEPARTMENT_COUNT';
export const SHOW_ENGLISH_DEPARTMENT_COUNT_ERROR =
  'SHOW_ENGLISH_DEPARTMENT_COUNT_ERROR';
export const SHOW_PHYSICS_DEPARTMENT_COUNT = 'SHOW_PHYSICS_DEPARTMENT_COUNT';
export const SHOW_PHYSICS_DEPARTMENT_COUNT_ERROR =
  'SHOW_PHYSICS_DEPARTMENT_COUNT_ERROR';
export const SHOW_CHEMISTRY_DEPARTMENT_COUNT =
  'SHOW_CHEMISTRY_DEPARTMENT_COUNT';
export const SHOW_CHEMISTRY_DEPARTMENT_COUNT_ERROR =
  'SHOW_CHEMISTRY_DEPARTMENT_COUNT_ERROR';
export const SHOW_MECHANICAL_DEPARTMENT_COUNT =
  'SHOW_MECHANICAL_DEPARTMENT_COUNT';
export const SHOW_MECHANICAL_DEPARTMENT_COUNT_ERROR =
  'SHOW_MECHANICAL_DEPARTMENT_COUNT_ERROR';
export const SHOW_SOFTWARE_DEPARTMENT_COUNT = 'SHOW_SOFTWARE_DEPARTMENT_COUNT';
export const SHOW_SOFTWARE_DEPARTMENT_COUNT_ERROR =
  'SHOW_SOFTWARE_DEPARTMENT_COUNT_ERROR';
export const SHOW_FEE_SECTION_COUNT = 'SHOW_FEE_SECTION_COUNT';
export const SHOW_FEE_SECTION_COUNT_ERROR = 'SHOW_FEE_SECTION_COUNT_ERROR';
export const SHOW_LIBRARY_COUNT = 'SHOW_LIBRARY_COUNT';
export const SHOW_LIBRARY_COUNT_ERROR = 'SHOW_LIBRARY_COUNT_ERROR';
export const SHOW_EXAMINATION_DEPARTMENT_COUNT =
  'SHOW_EXAMINATION_DEPARTMENT_COUNT';
export const SHOW_EXAMINATION_DEPARTMENT_COUNT_ERROR =
  'SHOW_EXAMINATION_DEPARTMENT_COUNT_ERROR';
export const SHOW_INCHARGE_CAMPUS_COUNT = 'SHOW_INCHARGE_CAMPUS_COUNT';
export const SHOW_INCHARGE_CAMPUS_COUNT_ERROR = 'SHOW_INCHARGE_CAMPUS_COUNT_ERROR';

//Applications Types
export const SHOW_CS_DEPARTMENT = 'SHOW_CS_DEPARTMENT';
export const SHOW_CS_DEPARTMENT_ERROR = 'SHOW_CS_DEPARTMENT_ERROR';
export const SHOW_URDU_DEPARTMENT = 'SHOW_URDU_DEPARTMENT';
export const SHOW_URDU_DEPARTMENT_ERROR =
  'SHOW_URDU_DEPARTMENT_ERROR';
export const SHOW_ISLAMIAT_DEPARTMENT = 'SHOW_ISLAMIAT_DEPARTMENT';
export const SHOW_ISLAMIAT_DEPARTMENT_ERROR =
  'SHOW_ISLAMIAT_DEPARTMENT_ERROR';
export const SHOW_LAW_DEPARTMENT = 'SHOW_LAW_DEPARTMENT';
export const SHOW_LAW_DEPARTMENT_ERROR =
  'SHOW_LAW_DEPARTMENT_ERROR';
export const SHOW_ECONOMICS_DEPARTMENT =
  'SHOW_ECONOMICS_DEPARTMENT';
export const SHOW_ECONOMICS_DEPARTMENT_ERROR =
  'SHOW_ECONOMICS_DEPARTMENT_ERROR';
export const SHOW_BUSINESS_DEPARTMENT = 'SHOW_BUSINESS_DEPARTMENT';
export const SHOW_BUSINESS_DEPARTMENT_ERROR =
  'SHOW_BUSINESS_DEPARTMENT_ERROR';
export const SHOW_COMMERCE_DEPARTMENT = 'SHOW_COMMERCE_DEPARTMENT';
export const SHOW_COMMERCE_DEPARTMENT_ERROR =
  'SHOW_COMMERCE_DEPARTMENT_ERROR';
export const SHOW_APPLIED_PHYSICS_DEPARTMENT =
  'SHOW_APPLIED_PHYSICS_DEPARTMENT';
export const SHOW_APPLIED_PHYSICS_DEPARTMENT_ERROR =
  'SHOW_APPLIED_PHYSICS_DEPARTMENT_ERROR';
export const SHOW_ELECTRICAL_DEPARTMENT =
  'SHOW_ELECTRICAL_DEPARTMENT';
export const SHOW_ELECTRICAL_DEPARTMENT_ERROR =
  'SHOW_ELECTRICAL_DEPARTMENT_ERROR';
export const SHOW_MATHEMATICS_DEPARTMENT =
  'SHOW_MATHEMATICS_DEPARTMENT';
export const SHOW_MATHEMATICS_DEPARTMENT_ERROR =
  'SHOW_MATHEMATICS_DEPARTMENT_ERROR';
export const SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT =
  'SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT';
export const SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_ERROR =
  'SHOW_INTERNATIONAL_RELATIONS_DEPARTMENT_ERROR';
export const SHOW_ENGLISH_DEPARTMENT = 'SHOW_ENGLISH_DEPARTMENT';
export const SHOW_ENGLISH_DEPARTMENT_ERROR =
  'SHOW_ENGLISH_DEPARTMENT_ERROR';
export const SHOW_PHYSICS_DEPARTMENT = 'SHOW_PHYSICS_DEPARTMENT';
export const SHOW_PHYSICS_DEPARTMENT_ERROR =
  'SHOW_PHYSICS_DEPARTMENT_ERROR';
export const SHOW_CHEMISTRY_DEPARTMENT =
  'SHOW_CHEMISTRY_DEPARTMENT';
export const SHOW_CHEMISTRY_DEPARTMENT_ERROR =
  'SHOW_CHEMISTRY_DEPARTMENT_ERROR';
export const SHOW_MECHANICAL_DEPARTMENT =
  'SHOW_MECHANICAL_DEPARTMENT';
export const SHOW_MECHANICAL_DEPARTMENT_ERROR =
  'SHOW_MECHANICAL_DEPARTMENT_ERROR';
export const SHOW_SOFTWARE_DEPARTMENT = 'SHOW_SOFTWARE_DEPARTMENT';
export const SHOW_SOFTWARE_DEPARTMENT_ERROR =
  'SHOW_SOFTWARE_DEPARTMENT_ERROR';
export const SHOW_FEE_SECTION = 'SHOW_FEE_SECTION';
export const SHOW_FEE_SECTION_ERROR = 'SHOW_FEE_SECTION_ERROR';
export const SHOW_LIBRARY = 'SHOW_LIBRARY';
export const SHOW_LIBRARY_ERROR = 'SHOW_LIBRARY_ERROR';
export const SHOW_EXAMINATION_DEPARTMENT =
  'SHOW_EXAMINATION_DEPARTMENT';
export const SHOW_EXAMINATION_DEPARTMENT_ERROR =
  'SHOW_EXAMINATION_DEPARTMENT_ERROR';
export const SHOW_INCHARGE_CAMPUS = 'SHOW_INCHARGE_CAMPUS';
export const SHOW_INCHARGE_CAMPUS_ERROR = 'SHOW_INCHARGE_CAMPUS_ERROR';
export const APPLICATION_LOADING = 'APPLICATION_LOADING';

//Apply Application Types
export const APPLY_APPLICATION_LOADING = 'APPLY_APPLICATION_LOADING';
export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';
export const SUBMIT_APPLICATION_ERROR = 'SUBMIT_APPLICATION_ERROR';

//Fee Chalan Types
export const CHALAN_LOADING = 'CHALAN_LOADING';
export const UPLOAD_CHALAN = 'UPLOAD_CHALAN';
export const UPLOAD_CHALAN_ERROR = 'UPLOAD_CHALAN_ERROR';
export const UPLOAD_PAID_CHALAN = 'UPLOAD_PAID_CHALAN';
export const UPLOAD_PAID_CHALAN_ERROR = 'UPLOAD_PAID_CHALAN_ERROR';
export const SHOW_CHALAN = 'SHOW_CHALAN';
export const SHOW_CHALAN_ERROR = 'SHOW_CHALAN_ERROR';
export const SHOW_PAID_CHALAN = 'SHOW_PAID_CHALAN';
export const SHOW_PAID_CHALAN_ERROR = 'SHOW_PAID_CHALAN_ERROR';
export const APPLICATION_ID = 'APPLICATION_ID';
export const APPLICATION_ID_ERROR = 'APPLICATION_ID_ERROR';

//Status Types
export const STATUS_LOADING = 'STATUS_LOADING';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR';
export const SHOW_STATUS = 'SHOW_STATUS';
export const SHOW_STATUS_ERROR = 'SHOW_STATUS_ERROR';

//Feedback Types
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SEND_FEEDBACK_ERROR = 'SEND_FEEDBACK_ERROR';

//Update Password Types
export const PASSWORD_LOADING = 'PASSWORD_LOADING';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

//Show Documents Types
export const DOCUMENT_LOADING = 'DOCUMENT_LOADING';
export const SHOW_DOCUMENTS = 'SHOW_DOCUMENTS';
export const SHOW_DOCUMENT_ERROR = 'SHOW_DOCUMENT_ERROR';
